# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Thilanga Pitigala
tagline:          "IO"
description:      'Proud dad of two girls, fallen in love and married to a software engineer. Thilanga enjoys time paying with geek toys, field hockey and FOSS.'
url:              http://pitigala.org

author:
  name:           'Thilanga Pitigala'
  url:            https://twitter.com/tpitigala

paginate:         2

# Custom vars
version:          1.0.0

github:
  repo:           github.com/thilanga/thilanga.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:
  Archive: '/archive'
  Feed: '/atom.xml'
