# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Thilanga Pitigala
tagline:          'Thilanga Pitigala'
description:      ''
url:              https://pitigala.org

author:
  name:           'Thilanga Pitigala'
  url:            https://pitigala.org

paginate:         2
google_analytics: 'UA-24228201-1'
emailme:          mailto:pittado@gmail.com

plugins:          [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/thilanga/thilanga.github.io

tags:

github_username:  thilanga
linkedin_username: thilanga


